  spring:
    application:
      name: ecommerce-backend

    datasource:
      url: ${datasource.url}
      username: ${datasource.username}
      password: ${datasource.password}

    jpa:
      hibernate:
        ddl-auto: update
      show-sql: true
      properties:
        hibernate:
          format_sql: true

    servlet:
      multipart:
        enabled: true
        max-file-size: 10MB
        max-request-size: 10MB

    config:
      import: optional:application-secret.yaml

    data:
      redis:
        host: localhost
        port: 6379

    cache:
      type: redis

  file:
    upload-dir: uploads

  jwt:
    secret: ${jwt.secret}
    access-token-expiration: ${jwt.access-token-expiration}
    refresh-token-expiration: ${jwt.refresh-token-expiration}

  razorpay:
    key: ${razorpay.key}
    secret: ${razorpay.secret}